# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
    ]
