# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170118_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='e_link',
            field=models.URLField(blank=True),
        ),
    ]
