# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='desc',
        ),
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
